In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import nltk
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
with open('rec_df.pickle', 'rb') as f:
    df = pickle.load(f)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100088 entries, 0 to 100087
Columns: 4419 entries, name to complexity
dtypes: float64(9), int64(4409), object(1)
memory usage: 3.3+ GB


In [3]:
df.columns

Index(['name', 'avg_sentiment_score', 'url', 'yr_pub', 'min_players',
       'max_players', 'avg_play_time', 'min_play_time', 'max_play_time',
       'min_age',
       ...
       'Video Game Theme: SEGA', 'Video Game Theme: Sonic the Hedgehog',
       'Video Game Theme: Super Mario Bros.', 'Video Game Theme: Tetris',
       'Webcomics: Dork Tower', 'Webcomics: Penny Arcade',
       'Word Games: First Letter Given', 'Word Games: Guess the Word',
       'Word Games: Sign Language', 'Word Games: Spelling / Letters'],
      dtype='object', length=4420)

In [5]:
df['avg_user_rating'].head()

KeyError: 'avg_user_rating'

In [55]:
df.columns

Index(['name', 'avg_sentiment_score', 'url', 'yr_pub', 'min_players',
       'max_players', 'avg_play_time', 'min_play_time', 'max_play_time',
       'min_age',
       ...
       'Video Game Theme: SEGA', 'Video Game Theme: Sonic the Hedgehog',
       'Video Game Theme: Super Mario Bros.', 'Video Game Theme: Tetris',
       'Webcomics: Dork Tower', 'Webcomics: Penny Arcade',
       'Word Games: First Letter Given', 'Word Games: Guess the Word',
       'Word Games: Sign Language', 'Word Games: Spelling / Letters'],
      dtype='object', length=4420)

In [ ]:
#var take in filters
#get board game idx
#reshape input
#run cos_sim on df and bg
#sort and find closest games

In [68]:
#'yr_pub',
rec_columns = ['avg_play_time','min_players','min_age','has_expansion','complexity','avg_sentiment_score']
#rec_columns = ['has_expansion','complexity']

In [65]:
df[['has_expansion','complexity']].head()

has_expansion  complexity
0              0        0.00
1              0        0.00
2              0        2.75
3              0        0.00
4              0        0.00

In [25]:
game_name = 'Pandemic'

In [11]:
game_name.lower()

'pandemic'

In [26]:
test = df[df['name']==game_name.title()].index.values

In [14]:
df.iloc[test]

name  avg_sentiment_score  Abstract Strategy  Action / Dexterity  \
57521  Pandemic                  1.0                  0                   0   

       Adventure  Age of Reason  American Civil War  American Indian Wars  \
57521          0              0                   0                     0   

       American Revolutionary War  American West  ...  \
57521                           0              0  ...   

       Word Games: Sign Language  Word Games: Spelling / Letters    yr_pub  \
57521                          0                               0  0.351287   

       min_players  max_players  avg_play_time  min_play_time  max_play_time  \
57521     0.000258    -0.044188      -0.003661       0.005317      -0.003661   

        min_age  complexity  
57521  0.081888    1.425255  

[1 rows x 4419 columns]

In [10]:
df.index.values

array([     0,      1,      2, ..., 100085, 100086, 100087])

In [69]:
test = df.loc[100][rec_columns].values.reshape(1,-1)
print(test)

[[30 2 0 0 1.0 0.9981]]


In [52]:
#get scores
drop_cols = ['name','url','avg_user_rating','bgg_adj_rating']

In [33]:
sorted(df['max_players'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 47,
 48,
 50,
 51,
 52,
 54,
 55,
 56,
 60,
 61,
 64,
 68,
 69,
 72,
 75,
 76,
 80,
 81,
 88,
 90,
 92,
 96,
 98,
 99,
 100,
 101,
 102,
 103,
 112,
 120,
 125,
 127,
 150,
 160,
 163,
 190,
 200,
 250,
 362,
 399,
 400,
 420,
 500,
 600,
 900,
 999,
 1000,
 2000,
 10000,
 11299]

In [34]:
df['max_players'].value_counts().tail(50)

42       6
27       5
52       5
102      4
500      4
120      4
39       3
29       3
31       3
88       2
34       2
68       2
150      2
101      2
54       2
160      1
399      1
112      1
76       1
51       1
72       1
55       1
69       1
45       1
56       1
900      1
250      1
61       1
125      1
190      1
47       1
362      1
400      1
43       1
96       1
64       1
163      1
92       1
90       1
420      1
37       1
38       1
600      1
11299    1
103      1
23       1
10000    1
81       1
2000     1
127      1
Name: max_players, dtype: int64

In [35]:
sorted(df['min_players'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 18,
 20,
 22,
 24,
 25,
 40,
 50]

In [37]:
df['min_players'].value_counts()

2     72660
1     14046
3      8205
4      2469
0      1837
6       243
5       224
8       219
7        64
10       44
12       22
9        21
15        7
20        5
11        4
13        4
16        4
14        3
40        2
18        1
22        1
24        1
25        1
50        1
Name: min_players, dtype: int64

In [38]:
sorted(df['avg_play_time'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 23,
 24,
 25,
 27,
 28,
 30,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 44,
 45,
 46,
 47,
 48,
 50,
 55,
 60,
 65,
 66,
 68,
 70,
 72,
 75,
 79,
 80,
 85,
 90,
 95,
 96,
 97,
 99,
 100,
 105,
 108,
 110,
 111,
 115,
 118,
 120,
 125,
 130,
 135,
 140,
 150,
 160,
 165,
 175,
 180,
 183,
 190,
 200,
 202,
 210,
 220,
 222,
 225,
 240,
 250,
 260,
 270,
 280,
 290,
 300,
 320,
 330,
 340,
 350,
 360,
 380,
 400,
 420,
 445,
 450,
 460,
 480,
 500,
 525,
 540,
 550,
 600,
 640,
 660,
 700,
 720,
 750,
 780,
 800,
 810,
 840,
 900,
 960,
 999,
 1000,
 1080,
 1180,
 1200,
 1260,
 1400,
 1440,
 1500,
 1620,
 1710,
 1740,
 1800,
 1920,
 1950,
 2000,
 2004,
 2005,
 2100,
 2160,
 2200,
 2400,
 2480,
 2880,
 3000,
 3600,
 3900,
 4000,
 4200,
 4500,
 4560,
 4800,
 5000,
 5400,
 6000,
 7920,
 8000,
 8400,
 8640,
 9000,
 9600,
 9999,
 10000,
 10080,
 12000,
 14400,
 17280,
 21600,
 22500,
 

In [39]:
df['avg_play_time'].value_counts()

0        22225
30       15846
60       11182
20        9195
45        6992
         ...  
38           1
165          1
10080        1
72000        1
72           1
Name: avg_play_time, Length: 177, dtype: int64

In [40]:
sorted(df['min_age'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 24,
 25,
 30,
 36,
 40,
 45,
 50,
 60,
 90,
 112,
 2017]

In [41]:
df['min_age'].value_counts()

0       22062
8       17480
12      15234
10      12582
6        6470
14       4485
7        4351
5        3968
4        3133
13       3011
3        1829
9        1534
18       1207
16        931
15        708
11        385
17        314
2         199
21        132
20         22
1          16
30         10
19          6
36          4
60          3
25          2
45          2
50          2
24          1
2017        1
22          1
40          1
112         1
90          1
Name: min_age, dtype: int64

In [19]:
df[df['avg_play_time']>=9999999]

name  avg_sentiment_score  \
15678  Office Space: The Game                  0.0   

                                              url  yr_pub  min_players  \
15678  https://boardgamegeek.com/boardgame/311320  2020.0            2   

       max_players  avg_play_time  min_play_time  max_play_time  min_age  ...  \
15678           10       30000000             30       30000000       16  ...   

       Video Game Theme: SEGA  Video Game Theme: Sonic the Hedgehog  \
15678                       0                                     0   

       Video Game Theme: Super Mario Bros.  Video Game Theme: Tetris  \
15678                                    0                         0   

       Webcomics: Dork Tower  Webcomics: Penny Arcade  \
15678                      0                        0   

       Word Games: First Letter Given  Word Games: Guess the Word  \
15678                               0                           0   

       Word Games: Sign Language  Word Games: Spelling / Letters  
15678                          0                               0  

[1 rows x 4420 columns]

In [ ]:
#Values for sliders

In [21]:
#Start with defaults? Note avg. play time is max. play time?
min_players = 0
max_players = 15000
avg_play_time = 30000000
min_age = 5000 
#remove expansions for the filter?
#has_expansion >= 0

#pick a rating(?)
avg_user_rating = 0
bgg_adj_rating = 0 

In [22]:
#avg. players, less choices?
Y_new = df[(df['min_players']>=min_players)&(df['max_players']<=max_players)&(df['avg_play_time']<=avg_play_time)&\
          (df['min_age']<=min_age)]

In [27]:
Y_new.iloc[test]

name  avg_sentiment_score  \
57521  Pandemic                  1.0   

                                             url  yr_pub  min_players  \
57521  https://boardgamegeek.com/boardgame/30549  2008.0            2   

       max_players  avg_play_time  min_play_time  max_play_time  min_age  ...  \
57521            4             45             45             45        8  ...   

       Video Game Theme: SEGA  Video Game Theme: Sonic the Hedgehog  \
57521                       0                                     0   

       Video Game Theme: Super Mario Bros.  Video Game Theme: Tetris  \
57521                                    0                         0   

       Webcomics: Dork Tower  Webcomics: Penny Arcade  \
57521                      0                        0   

       Word Games: First Letter Given  Word Games: Guess the Word  \
57521                               0                           0   

       Word Games: Sign Language  Word Games: Spelling / Letters  
57521                          0                               0  

[1 rows x 4420 columns]

In [51]:
Y_new.head()

name  avg_sentiment_score  \
0                                              Troia               0.0000   
1  Mauseschlau & Bärenstark: Wissen & Lachen – Un...              -0.3400   
2                  Quintessential: The Fifth Element               0.9983   
3                                      Wort für Wort               0.4939   
4                         Hannah Montana Secret Star               0.0000   

                                          url  yr_pub  min_players  \
0  https://boardgamegeek.com/boardgame/102580  2005.0            2   
1  https://boardgamegeek.com/boardgame/102595  2009.0            2   
2  https://boardgamegeek.com/boardgame/102597  2011.0            2   
3  https://boardgamegeek.com/boardgame/102598  1998.0            1   
4  https://boardgamegeek.com/boardgame/102599  2009.0            2   

   max_players  avg_play_time  min_play_time  max_play_time  min_age  ...  \
0            2             60             60             60        8  ...   
1            4             25             25             25        6  ...   
2            5             45             45             45       13  ...   
3            5             25             25             25        6  ...   
4            4             15             15             15        6  ...   

   Video Game Theme: SEGA  Video Game Theme: Sonic the Hedgehog  \
0                       0                                     0   
1                       0                                     0   
2                       0                                     0   
3                       0                                     0   
4                       0                                     0   

   Video Game Theme: Super Mario Bros.  Video Game Theme: Tetris  \
0                                    0                         0   
1                                    0                         0   
2                                    0                         0   
3                                    0                         0   
4                                    0                         0   

   Webcomics: Dork Tower  Webcomics: Penny Arcade  \
0                      0                        0   
1                      0                        0   
2                      0                        0   
3                      0                        0   
4                      0                        0   

   Word Games: First Letter Given  Word Games: Guess the Word  \
0                               0                           0   
1                               0                           0   
2                               0                           0   
3                               0                           0   
4                               0                           0   

   Word Games: Sign Language  Word Games: Spelling / Letters  
0                          0                               0  
1                          0                               0  
2                          0                               0  
3                          0                               0  
4                          0                               0  

[5 rows x 4420 columns]

In [54]:
cos_sim = cosine_similarity(X=df.iloc[test].drop(drop_cols,axis=1),Y=Y_new.drop(drop_cols,axis=1),dense_output=False)

KeyError: "['name' 'url' 'avg_user_rating' 'bgg_adj_rating'] not found in axis"

In [28]:
cos_sim.shape

(1, 2469)

In [29]:
idxs = np.argsort(cos_sim)[:,-11:-1]

In [30]:
print(idxs)

[[ 204  395  479    1  495  102 1055  221  975 2356]]


In [31]:
idxs.shape

(1, 10)

In [40]:
for idx in idxs[::-1]:
    print(idx)
    print(Y_new.iloc[idx][['name','url','min_players']])

[ 204  395  479    1  495  102 1055  221  975 2356]
                          name                                         url  \
7907              Gold und Rum    https://boardgamegeek.com/boardgame/6824   
16175         Wingy Crocodiles   https://boardgamegeek.com/boardgame/12473   
20542  200 Jahre Montgolfieren    https://boardgamegeek.com/boardgame/2804   
125               Quadragammon    https://boardgamegeek.com/boardgame/2594   
21127               White Lady    https://boardgamegeek.com/boardgame/4693   
3541             Money Monsoon   https://boardgamegeek.com/boardgame/14677   
43507    Assalto alla Jac Bank  https://boardgamegeek.com/boardgame/114819   
8426                 Kavelspel  https://boardgamegeek.com/boardgame/131807   
39966             Würfel-Duell    https://boardgamegeek.com/boardgame/1848   
95077            Müller & Sohn    https://boardgamegeek.com/boardgame/6874   

       min_players  
7907             4  
16175            4  
20542            4  
125  